package project_one.mybatis.dto;

public class Loginfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Loginfo.idkey
     *
     * @mbggenerated
     */
    private Integer idkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Loginfo.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Loginfo.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Loginfo.idkey
     *
     * @return the value of Loginfo.idkey
     *
     * @mbggenerated
     */
    public Integer getIdkey() {
        return idkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Loginfo.idkey
     *
     * @param idkey the value for Loginfo.idkey
     *
     * @mbggenerated
     */
    public void setIdkey(Integer idkey) {
        this.idkey = idkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Loginfo.username
     *
     * @return the value of Loginfo.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Loginfo.username
     *
     * @param username the value for Loginfo.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Loginfo.password
     *
     * @return the value of Loginfo.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Loginfo.password
     *
     * @param password the value for Loginfo.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    @Override
    public String toString() {
        return "Loginfo{" +
                "idkey=" + idkey +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}