package project_one.mybatis.dao;

import java.util.List;
import project_one.mybatis.dto.Loginfo;

public interface LoginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Loginfo
     *
     * @mbggenerated
     */
    int insert(Loginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Loginfo
     *
     * @mbggenerated
     */
    List<Loginfo> selectAll();

    Loginfo selectOneInfo(String username);
}